name: CI Workflow

on:
  pull_request:
    types:
      - opened
    branches:
      - main

jobs:
  first-job:
    runs-on: ubuntu-latest

    env:
      DB DATABASE: health_check
      DB_USERNAME: ${{secrets.DATABASE_USERNAME}}
      DB_PASSWORD: ${{secrets.DATABASE_PASSWORD}}
      DB_URL: ${{secrets.DATABASE_URL}}

    steps:
      - name: first step
        run: echo "first workflow!"

      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: start DB
        run:
          sudo /etc/init.d/mysql start
          mysql -h 127.0.0.1 -e "CREATE DATABASE IF NOT EXISTS $DB_DATABASE;" -u$DB_USERNAME -p$DB_PASSWORD
      - name: Build Maven
        run: mvn clean -B package --file pom.xml