name: check packer

on:
  pull_request:
    types:
      - opened
    branches:
      - main

jobs:
  validate-packer-template:
     runs-on: ubuntu-latest
     steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Setup `packer`
        uses: hashicorp/setup-packer@main
        id: setup
        with:
          version: "latest"
    
      - name: Init Packer
        run : packer init .
      
      - name: check the format
        run:  packer fmt --check  packer-config.pkr.hcl
        
      - name: validate the template
        run: packer validate packer-config.pkr.hcl