name: check packer

on:
  pull_request:
    types:
      - opened
    branches:
      - main

jobs:
  validate-packer-validate-build:
     runs-on: ubuntu-latest
     env:
      DB_USERNAME: ${{secrets.DATABASE_USERNAME}}
      DB_PASSWORD: ${{secrets.DATABASE_PASSWORD}}
      DB_URL: ${{secrets.DATABASE_URL}}
      FIRST_NAME: ${{secrets.FIRST_NAME}}
      LAST_NAME: ${{secrets.LAST_NAME}}
      USER_NAME: ${{secrets.USER_NAME}}
      PASSWORD: ${{secrets.PASSWORD}}
      UPDATED_FIRST_NAME: ${{secrets.UPDATED_FIRST_NAME}}
      UPDATED_LAST_NAME: ${{secrets.UPDATED_LAST_NAME}}
      PKR_VAR_project_id: ${{secrets.PROJECT_ID}}
      PKR_VAR_source_image_family: ${{secrets.SOURCE_IMAGE_FAMILY}}
      PKR_VAR_zone: ${{secrets.IMAGE_ZONE}}
      PKR_VAR_ssh_username: ${{secrets.SSH_USERNAME}}
      PKR_VAR_network: ${{secrets.IMAGE_NETWORK}}
      PKR_VAR_image_name: ${{secrets.IMAGE_NAME}}

     steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      
      - name: start DB
        run:
          sudo /etc/init.d/mysql start
          mysql -h 127.0.0.1 -e "CREATE DATABASE IF NOT EXISTS $DB_DATABASE;" -u$DB_USERNAME -p$DB_PASSWORD
      
      - name: compile the source code
        run: mvn clean compile --file pom.xml   
      
      - name: test using Maven
        run: mvn clean test --file pom.xml  

      - name: Setup `packer`
        uses: hashicorp/setup-packer@main
        id: setup
        with:
          version: "latest"
          
      - name: Setup packer
        uses: hashicorp/setup-packer@main
        id: setup
        with:
          version: "latest"

      - name: Init Packer
        run : packer init packer

      - name: check the packer template
        run: packer fmt --check  packer/packer-config.pkr.hcl

      - name: validate packer 
        run: packer validate -var "DB_URL=${DB_URL}" -var "DB_USERNAME=${DB_USERNAME}" -var "DB_PASSWORD=${DB_PASSWORD}" packer

      - name: build Image
        run : packer build -var "DB_URL=${DB_URL}" -var "DB_USERNAME=${DB_USERNAME}" -var "DB_PASSWORD=${DB_PASSWORD}" packer